import React from 'react';
import Head from "next/head";

function Layout({children}) {
    return (
        <div>
            <Head>
                <title>Pokedex</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>
                {children} {/* children means anything you put inside this function component */}
            </div>

        </div>
    )
}

export default Layout
